---
- name: symlink release
  file: >
    src={{ deploy_release_dir }}
    dest={{ deploy_application_home }}/current
    state=link
    owner={{ ansible_ssh_user }}
    group={{ ansible_ssh_user }}
    force=yes

- name: 'cleanup application releases'
  shell: "ls -1 | sort -r | awk 'NR>{{ deploy_update_code_git.preserve_releases | default(5) }}' | xargs rm -rf"
  args:
    chdir: '{{ deploy_application_home }}/{{ deploy_metadata_defaults.release_dir_name }}'
